-   id: make-lint
    name: Run linters on the project.
    description: This hook runs linters on the project.
    entry: make lint
    language: system

-   id: make-format
    name: Run formatters on the project.
    description: This hook runs formatters on the project.
    entry: make format
    language: system

-   id: make-test
    name: Run tests on the project.
    description: This hook runs tests on the project.
    entry: make test
    language: system

-   id: update-version
    name: Update the version of the project.
    description: This hook updates the version of the project.
    entry: make update-version
    language: system
