[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pre-commit-hooks"
version = "0.0.1"
description = ""
dependencies = ["pre-commit ==3.3.2"]

[project.optional-dependencies]
dev = ["build ==0.10.0"]
